### ISSUE TITLE
Regen crashes the game

### ISSUE THREAD

**Issue by ericek111** [ericek111/lixkopack#2]
```
-- Head --
Thread: Client thread
Stacktrace:
	at me.lixko.lixkopack.modules.Regen.onUpdate(Regen.java:17)
	at me.lixko.lixkopack.EventHandler.onUpdate(EventHandler.java:38)
	at net.minecraft.client.entity.EntityPlayerSP.onUpdate(EntityPlayerSP.java:221)
	at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:1632)
	at net.minecraft.world.World.updateEntity(World.java:1607)
```

**Comment by ericek111** [comment]
Fixed.
